apiVersion: v1
kind: Service
metadata:
  name: api-2
  labels:
    app: inspectorgadget
spec:
  selector:
    app: inspectorgadget
    tier: api-2
  type: ClusterIP
  ports:
  - port: 80 # Expose port 80 over the cluster IP
    targetPort: http # Reference a named port in the deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inspectorgadget
      tier: api-2
  template:
    metadata:
      labels:
        app: inspectorgadget
        tier: api-2
    spec:
      containers:
      - name: inspectorgadget
        image: jelledruyts/inspectorgadget
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        env:
        - name: tier
          value: "API 2"
        - name: InfoMessage
          value: "You're on the API 2 tier"
        - name: BackgroundColor
          value: "#fe9a2e"